### ISSUE TITLE
APIs throw Auth Error randomly

### ISSUE THREAD

**Issue by pavankumar2203** [ultradns/python_rest_api_client#5]
I am using the ultra_rest_client APIs. I get 2 types of error randomly. There are about 100 API calls being made sequentially. Can someone please let me know why these exceptions are thrown ??

Error 1:

raise AuthError(r1.json())

src.dns.ultra_rest_client.connection.AuthError: [{'errorMessage': 'System Error ', 'errorCode': 9999}]

Error 2:

raise AuthError(r1.json())

src.dns.ultra_rest_client.connection.AuthError: {'errorMessage': 'invalid_grant:Token not found, expired or invalid.', 'error_description': '60001: invalid_grant:Token not found, expired or invalid.', 'errorCode': 60001, 'error': 'invalid_grant'}

**Comment by tfullert** [comment]
We'll have to look into that first Error, I'm not familiar with the errorCode value of 9999 (sounds like a catch all though).  As for Error 2, there's something wrong with the authentication token.  It's possible it expired but it looks like the code in _connection.py_ attempts to refresh (get a new token using the refresh_token) and then try the call again.  How long do the 100 calls take to perform?  Probably what's happening is that the access token has expired and so the code attempts to get a new one with the refresh token.  The refresh token can also expire (I think after 15 minutes) and if it expires it doesn't look like the code handles that in anyway.  It just throws an AuthError which you would need to catch and process (i.e. request a new access/refresh token pair).

**Comment by tfullert** [comment]
@pavankumar2203 I couldn't find information regarding the errorCode values for the rest API but the SOAP API documentation has the error codes in the documentation and there is a general _system_ error of 9999.  I also found some informal references to an error code of 9999 in the REST API and it sounds like they're generated for failed database transactions.  For more specific details regarding the error you might have to tweak the _do_call method to get it to output the message that accompanies the error code.

**Comment by pavankumar2203** [comment]
@tfullert : Thanks for looking at it. I can add a retry logic for Error 2 if it fails. But I am not sure how many times I need to retry for error 1(may be until it succeeds ??).

These ~100 calls happen in the span of ~90 minutes. To be precise its about about 2-3 API calls every minute. In between the calls I have some other code to be executed. Error 9999 is what I am not able find the root cause. Meanwhile, I will try to print more information in the _do_call method and see if it helps.

**Comment by tfullert** [comment]
Hey @pavankumar2203 I did a bit more research on the refresh token and I found the following information:

- The refresh token expires after a single use, but has no time limit.
- Only one refresh token is valid at a time.
- If you use your username and password to acquire a new access token and refresh token, the old refresh token will automatically become expired.

So my initial assumption that the refresh token was expiring is wrong.  However, over a 90 minute period it is possible that perhaps _auth_ is being called multiple times on an object.  Do you ever call _auth_ explicitly or do you save the refresh_token outside of the client object?

It also might help to output a message every time the _auth_ or __refresh_ methods are called.

**Comment by pavankumar2203** [comment]
@tfullert . Now that makes sense why I am getting Error 2. I am making multiple RestApiClient objects. So the refresh tokens get expired as you say. I will take care of that.

**Comment by tfullert** [comment]
yeah, you should probably just create one and reuse it.  If you're running these requests sequentially that shouldn't be a problem.  Good luck!  Let me know how it goes.
